@baseUrl = http://localhost:8000


###
GET {{baseUrl}}/view

###
GET {{baseUrl}}/patient/P008

###
GET {{baseUrl}}/sort?sort_by=height

###
POST {{baseUrl}}/create
Content-Type: application/json

{
  "id": "P006",
  "name": "John Doe",
  "city": "New York",
  "age": 30,
  "gender": "male",
  "height": 175.5,
  "weight": 70.2
}

###
PUT {{baseUrl}}/edit/P006
Content-Type: application/json

{
  "name": "John Doe Updated",
  "city": "Los Angeles",
  "age": "31"
}  

###
DELETE {{baseUrl}}/delete/P006