print("Welcome to Band Name Generator!!\n")
print("----------------------------------")
city_name = input("Please enter a name of city you grew up!!\n")
print("----------------------------------")
pet_name = input("Please enter a name of your pet!!\n")
print("----------------------------------")
print("Your band name is: " + city_name + " " + pet_name)
print("----------------------------------")